In [1]:
import pandas as pd
import numpy as np

In [2]:
inequality = pd.read_csv("final_datasets_inequality.csv")

In [3]:
inequality.head()

,Year,CPI,percentage_cpi,PCE_food_billions_of_dollars,PCE_energy_goods_services_billions_of_dollars,PCE_food_percentage,PCE_energy_goods_services_percentage,GDP_in_Billions,percentage_gdp,median_household_income_2021,...,pce_energy_change,gdp_change,median_income_change,gdp_percap_change,first_change,second_change,third_change,fourth_change,fifth_change,top_five_change
0,1984,103.9,NaN,291.100000,193.091667,NaN,NaN,4037.61400,NaN,54744.62,...,0.000000,0.00000,0.00,0,0,0,0,0,0,0
1,1985,107.6,3.56,302.950000,199.541667,4.07,3.34,4338.98050,7.46,55768.24,...,6.450000,301.36650,1023.62,1158,178,687,1177,1738,4232,8580
2,1986,109.6,1.86,316.416667,178.583333,4.45,-10.50,4579.63250,5.55,57777.04,...,-14.508333,542.01850,3032.42,2210,338,1313,2417,3659,8750,17250
3,1987,113.6,3.65,324.316667,185.341667,2.50,3.78,4855.21625,6.02,58467.08,...,-7.750000,817.60225,3722.46,2823,696,2044,3617,5599,12776,24226
4,1988,118.3,4.14,342.791667,194.075000,5.70,4.71,5236.43800,7.85,58949.27,...,0.983333,1198.82400,4204.65,3966,1029,2777,4853,7470,16638,30441

In [4]:
inequality.to_html("inequality.html")